// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    401: typeof import('./views/exception/401.vue')['default']
    404: typeof import('./views/exception/404.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    IconFa6solidLanguage: typeof import('~icons/fa/6solid-language')['default']
    IconFa6SolidLanguage: typeof import('~icons/fa6-solid/language')['default']
    IconLaLanguage: typeof import('~icons/la/language')['default']
    ILaLanguage: typeof import('~icons/la/language')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
