#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# pnpm 
# options: --quiet(-q) 禁止所有 CLI 输出（默认值：false）
pnpm exec lint-staged -q

# npm yarn
# npx lint-staged

# yarn berry(yarn2+)
# yarn exec lint-staged
